FROM golang:1.22-alpine AS builder
RUN apk add --no-cache git ca-certificates
WORKDIR /app
COPY . .
RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-w -s" -o /bin/stateserver ./cmd/stateserver

FROM alpine:3.19
RUN apk add --no-cache ca-certificates wget
COPY --from=builder /bin/stateserver /stateserver
EXPOSE 9001
ENTRYPOINT ["/stateserver"]
