FROM golang:1.22-alpine AS builder
RUN apk add --no-cache git ca-certificates
WORKDIR /app
COPY . .
RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-w -s" -o /bin/loadbalancer ./cmd/loadbalancer

FROM alpine:3.19
RUN apk add --no-cache ca-certificates
COPY --from=builder /bin/loadbalancer /loadbalancer
EXPOSE 8080 2112
ENTRYPOINT ["/loadbalancer"]
